[package]
name = "wu"
version = "0.1.0"
authors = ["Adam Rutkowski <hq@mtod.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
include_dir = "0.6.2"
pulldown-cmark = "0.8.0"
